export default {
  CONTINENTS: 'CONTINENTS',
  ALL_CASES: 'ALL_CASES',
  RECORD_DATES: 'RECORD_DATES',
  RECORD_VALUES: 'RECORD_VALUES',
  NEW_COUNTRY: 'NEW_COUNTRY',
  NEW_COUNTRY_NAME: 'NEW_COUNTRY_NAME',
  NEW_TOP_COUNTRY: 'NEW_TOP_COUNTRY',
  REC_RES: 'REC_RES'
};
